#-------------------------------
# General Site Settings
title: blog
logo: # You can add own logo. For example '/images/logo.png'.
description: Random musings of a slightly crazed engineer of society.
baseurl: "/taimoor.github.io" # The subpath of your site, e.g. /blog
url: "https://ranataimoor067.github.io/taimoor.github.io/" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Taimoor
  avatar: '/images/profiles/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: here u find
  description: Thoughts, stories and ideas.
  image: '/images/profiles/hero.jpg'


#-------------------------------
# Contact Settings
contact:
  email: ranatamoor067@gmail.com # Add your email for contant form
  # description: 

# NOTE
# Aditu theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
- {icon: "ion-logo-twitter", link: ""}
- {icon: "ion ion-logo-youtube", link: ""}
- {icon: "ion ion-md-mail", link: "mailto:ranatamoor067@gmail.com"}
- {icon: "ion ion-md-whatsapp", link: "https://wa.me/+923237606011"}


#twitter-username: sunnya97

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Taimoor


#-------------------------------
# Google Analytics
# google-analytics: UA-168754428-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /blog/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 18
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


collections:
  quotes:
    output: true
    permalink: /quotes/:path/
